# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_ui(object):
    def setupUi(self, main_ui):
        main_ui.setObjectName("main_ui")
        main_ui.resize(1065, 595)
        self.central_widget = QtWidgets.QWidget(main_ui)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.central_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(315, 290))
        self.groupBox.setMaximumSize(QtCore.QSize(315, 290))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.sb_samples = QtWidgets.QSpinBox(self.groupBox)
        self.sb_samples.setMaximum(99999999)
        self.sb_samples.setProperty("value", 4096)
        self.sb_samples.setObjectName("sb_samples")
        self.gridLayout.addWidget(self.sb_samples, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.sb_n = QtWidgets.QSpinBox(self.groupBox)
        self.sb_n.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sb_n.setMinimum(1)
        self.sb_n.setMaximum(9999)
        self.sb_n.setProperty("value", 1)
        self.sb_n.setObjectName("sb_n")
        self.gridLayout.addWidget(self.sb_n, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        self.sb_phase = QtWidgets.QSpinBox(self.groupBox)
        self.sb_phase.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sb_phase.setMaximum(360)
        self.sb_phase.setObjectName("sb_phase")
        self.gridLayout.addWidget(self.sb_phase, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 3, 1, 1)
        self.bn_add = QtWidgets.QPushButton(self.groupBox)
        self.bn_add.setMaximumSize(QtCore.QSize(315, 16777215))
        self.bn_add.setObjectName("bn_add")
        self.gridLayout.addWidget(self.bn_add, 11, 0, 1, 5)
        self.sb_frequency = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_frequency.setMinimumSize(QtCore.QSize(100, 0))
        self.sb_frequency.setDecimals(2)
        self.sb_frequency.setMaximum(99999999.99)
        self.sb_frequency.setProperty("value", 1.0)
        self.sb_frequency.setObjectName("sb_frequency")
        self.gridLayout.addWidget(self.sb_frequency, 3, 1, 1, 1)
        self.sb_amplitude = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_amplitude.setMinimumSize(QtCore.QSize(100, 0))
        self.sb_amplitude.setDecimals(2)
        self.sb_amplitude.setMaximum(99999999.99)
        self.sb_amplitude.setProperty("value", 1.0)
        self.sb_amplitude.setObjectName("sb_amplitude")
        self.gridLayout.addWidget(self.sb_amplitude, 4, 1, 1, 1)
        self.sb_offset = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_offset.setMinimumSize(QtCore.QSize(100, 0))
        self.sb_offset.setDecimals(2)
        self.sb_offset.setMaximum(99999999.99)
        self.sb_offset.setObjectName("sb_offset")
        self.gridLayout.addWidget(self.sb_offset, 5, 1, 1, 1)
        self.sb_factor = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.sb_factor.setMinimumSize(QtCore.QSize(100, 0))
        self.sb_factor.setDecimals(2)
        self.sb_factor.setMaximum(99999999.99)
        self.sb_factor.setObjectName("sb_factor")
        self.gridLayout.addWidget(self.sb_factor, 8, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bn_delete = QtWidgets.QPushButton(self.groupBox_3)
        self.bn_delete.setObjectName("bn_delete")
        self.gridLayout_3.addWidget(self.bn_delete, 1, 0, 1, 1)
        self.bn_delete_all = QtWidgets.QPushButton(self.groupBox_3)
        self.bn_delete_all.setObjectName("bn_delete_all")
        self.gridLayout_3.addWidget(self.bn_delete_all, 1, 1, 1, 1)
        self.table_sinus = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_sinus.setObjectName("table_sinus")
        self.table_sinus.setColumnCount(4)
        self.table_sinus.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.table_sinus, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SignalBasePlot = QtWidgets.QWidget(self.groupBox_2)
        self.SignalBasePlot.setObjectName("SignalBasePlot")
        self.gridLayout_4.addWidget(self.SignalBasePlot, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.central_widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        main_ui.setCentralWidget(self.central_widget)

        self.retranslateUi(main_ui)
        QtCore.QMetaObject.connectSlotsByName(main_ui)

    def retranslateUi(self, main_ui):
        _translate = QtCore.QCoreApplication.translate
        main_ui.setWindowTitle(_translate("main_ui", "windowTitle"))
        self.groupBox.setTitle(_translate("main_ui", "Eingabe"))
        self.label_2.setText(_translate("main_ui", "Amplitude"))
        self.label.setText(_translate("main_ui", "Phasenverschiebung"))
        self.label_11.setText(_translate("main_ui", "Anzahl Perioden"))
        self.label_12.setText(_translate("main_ui", "Anzahl Sampels"))
        self.label_3.setText(_translate("main_ui", "Frequenz"))
        self.label_9.setText(_translate("main_ui", "Faktor"))
        self.label_5.setText(_translate("main_ui", "Hz"))
        self.label_4.setText(_translate("main_ui", "Offset"))
        self.label_6.setText(_translate("main_ui", "V"))
        self.label_8.setText(_translate("main_ui", "°"))
        self.label_10.setText(_translate("main_ui", "V"))
        self.bn_add.setText(_translate("main_ui", "Hinzufügen"))
        self.groupBox_3.setTitle(_translate("main_ui", "Aktuell"))
        self.bn_delete.setText(_translate("main_ui", "Löschen"))
        self.bn_delete_all.setText(_translate("main_ui", "Alle Löschen"))
        item = self.table_sinus.horizontalHeaderItem(0)
        item.setText(_translate("main_ui", "Frequenz"))
        item = self.table_sinus.horizontalHeaderItem(1)
        item.setText(_translate("main_ui", "Amplitude"))
        item = self.table_sinus.horizontalHeaderItem(2)
        item.setText(_translate("main_ui", "Anzahl Perioden"))
        item = self.table_sinus.horizontalHeaderItem(3)
        item.setText(_translate("main_ui", "Phasenverschiebung"))
        self.groupBox_2.setTitle(_translate("main_ui", "Ausgabe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("main_ui", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("main_ui", "Tab 2"))


