# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_ui(object):
    def setupUi(self, main_ui):
        main_ui.setObjectName("main_ui")
        main_ui.resize(1417, 1374)
        main_ui.setMinimumSize(QtCore.QSize(1206, 1000))
        self.central_widget = QtWidgets.QWidget(main_ui)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.FftPlot = QtWidgets.QGridLayout()
        self.FftPlot.setSpacing(6)
        self.FftPlot.setObjectName("FftPlot")
        self.gridLayout_7.addLayout(self.FftPlot, 1, 0, 1, 9)
        self.line_2 = QtWidgets.QFrame(self.central_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 9, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 9, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.central_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 9, 1, 1, 1)
        self.cb_fft_ch2 = QtWidgets.QCheckBox(self.central_widget)
        self.cb_fft_ch2.setChecked(True)
        self.cb_fft_ch2.setObjectName("cb_fft_ch2")
        self.gridLayout_7.addWidget(self.cb_fft_ch2, 9, 3, 1, 1)
        self.cb_fft_ch1 = QtWidgets.QCheckBox(self.central_widget)
        self.cb_fft_ch1.setChecked(True)
        self.cb_fft_ch1.setObjectName("cb_fft_ch1")
        self.gridLayout_7.addWidget(self.cb_fft_ch1, 9, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.central_widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 9, 7, 1, 1)
        self.FftPlotToolbar = QtWidgets.QHBoxLayout()
        self.FftPlotToolbar.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.FftPlotToolbar.setSpacing(6)
        self.FftPlotToolbar.setObjectName("FftPlotToolbar")
        self.gridLayout_7.addLayout(self.FftPlotToolbar, 9, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.central_widget)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_7.addWidget(self.progressBar, 9, 8, 1, 1, QtCore.Qt.AlignRight)
        self.widget = QtWidgets.QWidget(self.central_widget)
        self.widget.setMinimumSize(QtCore.QSize(0, 263))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 2, 1, 1)
        self.bn_cancle_measure = QtWidgets.QPushButton(self.groupBox_2)
        self.bn_cancle_measure.setObjectName("bn_cancle_measure")
        self.gridLayout_4.addWidget(self.bn_cancle_measure, 1, 4, 1, 1)
        self.bn_start_measure = QtWidgets.QPushButton(self.groupBox_2)
        self.bn_start_measure.setObjectName("bn_start_measure")
        self.gridLayout_4.addWidget(self.bn_start_measure, 1, 3, 1, 1)
        self.SinusSignalPlot = QtWidgets.QHBoxLayout()
        self.SinusSignalPlot.setSpacing(6)
        self.SinusSignalPlot.setObjectName("SinusSignalPlot")
        self.gridLayout_4.addLayout(self.SinusSignalPlot, 0, 0, 1, 5)
        self.cb_subsinus_visible = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_subsinus_visible.setObjectName("cb_subsinus_visible")
        self.gridLayout_4.addWidget(self.cb_subsinus_visible, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMaximumSize(QtCore.QSize(295, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setMinimumSize(QtCore.QSize(275, 206))
        self.widget_2.setMaximumSize(QtCore.QSize(275, 206))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.sb_abs = QtWidgets.QSpinBox(self.widget_2)
        self.sb_abs.setMinimum(1)
        self.sb_abs.setMaximum(9999)
        self.sb_abs.setProperty("value", 1)
        self.sb_abs.setObjectName("sb_abs")
        self.gridLayout_5.addWidget(self.sb_abs, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 3, 0, 1, 1)
        self.bn_calc_sinus = QtWidgets.QPushButton(self.widget_2)
        self.bn_calc_sinus.setObjectName("bn_calc_sinus")
        self.gridLayout_5.addWidget(self.bn_calc_sinus, 5, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_offset = QtWidgets.QLineEdit(self.widget_2)
        self.le_offset.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.le_offset.setObjectName("le_offset")
        self.gridLayout_5.addWidget(self.le_offset, 0, 1, 1, 1)
        self.le_factor = QtWidgets.QLineEdit(self.widget_2)
        self.le_factor.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.le_factor.setObjectName("le_factor")
        self.gridLayout_5.addWidget(self.le_factor, 2, 1, 1, 1)
        self.le_samples = QtWidgets.QLineEdit(self.widget_2)
        self.le_samples.setObjectName("le_samples")
        self.gridLayout_5.addWidget(self.le_samples, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(368, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(368, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bn_delete = QtWidgets.QPushButton(self.groupBox_3)
        self.bn_delete.setObjectName("bn_delete")
        self.gridLayout_3.addWidget(self.bn_delete, 1, 1, 1, 1)
        self.bn_delete_all = QtWidgets.QPushButton(self.groupBox_3)
        self.bn_delete_all.setObjectName("bn_delete_all")
        self.gridLayout_3.addWidget(self.bn_delete_all, 1, 2, 1, 1)
        self.bn_add = QtWidgets.QPushButton(self.groupBox_3)
        self.bn_add.setObjectName("bn_add")
        self.gridLayout_3.addWidget(self.bn_add, 1, 0, 1, 1)
        self.table_sinus = QtWidgets.QTableWidget(self.groupBox_3)
        self.table_sinus.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_sinus.setCornerButtonEnabled(False)
        self.table_sinus.setObjectName("table_sinus")
        self.table_sinus.setColumnCount(3)
        self.table_sinus.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.table_sinus.setHorizontalHeaderItem(2, item)
        self.table_sinus.horizontalHeader().setDefaultSectionSize(110)
        self.table_sinus.horizontalHeader().setHighlightSections(False)
        self.table_sinus.horizontalHeader().setStretchLastSection(True)
        self.table_sinus.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.table_sinus, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 9)
        self.hs_fft_slider = QtWidgets.QSlider(self.central_widget)
        self.hs_fft_slider.setMinimumSize(QtCore.QSize(200, 0))
        self.hs_fft_slider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hs_fft_slider.setMinimum(1)
        self.hs_fft_slider.setMaximum(100)
        self.hs_fft_slider.setSingleStep(10)
        self.hs_fft_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hs_fft_slider.setObjectName("hs_fft_slider")
        self.gridLayout_7.addWidget(self.hs_fft_slider, 9, 6, 1, 1)
        main_ui.setCentralWidget(self.central_widget)

        self.retranslateUi(main_ui)
        QtCore.QMetaObject.connectSlotsByName(main_ui)

    def retranslateUi(self, main_ui):
        _translate = QtCore.QCoreApplication.translate
        main_ui.setWindowTitle(_translate("main_ui", "windowTitle"))
        self.label.setText(_translate("main_ui", "FFT Zoom"))
        self.cb_fft_ch2.setText(_translate("main_ui", "CH2"))
        self.cb_fft_ch1.setText(_translate("main_ui", "CH1"))
        self.progressBar.setFormat(_translate("main_ui", "Done"))
        self.groupBox_2.setTitle(_translate("main_ui", "Ausgabe"))
        self.bn_cancle_measure.setText(_translate("main_ui", "Messung abbrechen"))
        self.bn_start_measure.setText(_translate("main_ui", "Messung Starten"))
        self.cb_subsinus_visible.setText(_translate("main_ui", "Sub Sinus anzeigne"))
        self.groupBox.setTitle(_translate("main_ui", "Signal generieren"))
        self.label_10.setText(_translate("main_ui", "V"))
        self.label_11.setText(_translate("main_ui", "Anzahl Perioden"))
        self.label_9.setText(_translate("main_ui", "Faktor"))
        self.label_12.setText(_translate("main_ui", "Anzahl Sampels"))
        self.bn_calc_sinus.setText(_translate("main_ui", "Signal generieren"))
        self.label_4.setText(_translate("main_ui", "Offset"))
        self.groupBox_3.setTitle(_translate("main_ui", "Sinus erzeugen"))
        self.bn_delete.setText(_translate("main_ui", "Löschen"))
        self.bn_delete_all.setText(_translate("main_ui", "Alle Löschen"))
        self.bn_add.setText(_translate("main_ui", "hinzufügen"))
        item = self.table_sinus.horizontalHeaderItem(0)
        item.setText(_translate("main_ui", "Frequenz [Hz]"))
        item = self.table_sinus.horizontalHeaderItem(1)
        item.setText(_translate("main_ui", "Amplitude [V]"))
        item = self.table_sinus.horizontalHeaderItem(2)
        item.setText(_translate("main_ui", "Phase [°]"))


